---
# tasks file for get_access_token
- block:
  - name: Make sure that a value for the variable 'offline_token' is defined
    ansible.builtin.assert:
      that:
        - offline_token is defined
      success_msg: "'offline_token' is defined, continuing"
      fail_msg: "'offline_token' must be defined. you can generate an offline token from https://access.redhat.com/management/api"

  - name: Get the access token
    ansible.builtin.uri:
      url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
      method: POST
      body_format: form-urlencoded
      body:
        grant_type: refresh_token
        client_id: rhsm-api
        refresh_token: "{{ offline_token }}"
    register: login_result

  - name: set a fact for the access_token
    ansible.builtin.set_fact:
      access_token: "{{ login_result.json.access_token }}"
  when: access_token is not defined
